apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  labels:
    app: collector
  name: collector
  namespace: punedev
spec:
  podManagementPolicy: OrderedReady
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: collector
    spec:
      containers:
        - env:
            - name: LOGICMONITOR_ACCOUNT
              value: ''
            - name: LOGICMONITOR_BEARER_TOKEN
              value: ''
            - name: LOGICMONITOR_ACCESS_ID
              value: ''
            - name: LOGICMONITOR_ACCESS_KEY
              value: ''
            - name: LOGICMONITOR_OTEL_NAME
              value: lmapmloadgentopology
            - name: LOGICMONITOR_OTEL_NAMESPACE
              value: punedev
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: logicmonitor/lmotel:latest
          imagePullPolicy: IfNotPresent
          name: lmotel
          resources: { }
          securityContext: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
