apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: collector
  name: collector
  namespace: punedev
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: healthcheck
      port: 13133
      protocol: TCP
      targetPort: 13133
    - name: http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: pprof
      port: 1777
      protocol: TCP
      targetPort: 1777
  selector:
    app: collector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: { }
